### ISSUE TITLE
BrainPTM has 7 labels?

### ISSUE THREAD

**Issue by ABC67876** [zhaoziheng/SAT-DS#2]
Appreciate for your work and kind share.
README states that BrainPTM has 7 labels.
But in processor.py, labels contains 4 structures and a 'brain'.
Is README wrong?

**Comment by zhaoziheng** [comment]
Hi, thanks for your interest in our work.

We do merge some labels when loading the data samples, i.e., the loader.py in Step 3. 
In this case, we merge 'Left Optic Radiation' and 'Right Optic Radiation' into 'Optic Radiation', 'Left Corticospinal Tract' and 'Right Corticospinal Tract' into 'Corticospinal Tract'.
Therefore, the loader's output contains two additional labels than the raw data. 

Sorry I missed this detail before, I have added it to the README.
